// Build-time fetch of ProjectOS public registry.
// The registry is generated by ProjectOS/agent/export_public_registry.py
// and committed to its public repo at data/public-registry.json.

const REGISTRY_URL =
  "https://raw.githubusercontent.com/vincentmaox/Object-OS-CC/main/data/public-registry.json";

export interface LastAction {
  message: string;
  date: string; // YYYY-MM-DD
}

export interface PublicProject {
  name: string;
  description: string;
  stage: string;
  freq_total: number | null;
  freq_suggestion: string | null;
  last_action: LastAction | null;
  github_url: string | null;
  cover_image?: string | null;
  featured?: boolean;
  showcase_rank?: number | null;
  tech_stack: string[];
}

export interface PublicRegistry {
  generated_at: string;
  count: number;
  projects: PublicProject[];
}

const STAGE_RANK: Record<string, number> = {
  "All-in": 0,
  "活跃": 1,
  "野化": 2,
  "Watch": 3,
  "停滞": 4,
  "已归档": 5,
  "Kill": 6,
};

function rankStage(s: string): number {
  return STAGE_RANK[s] ?? 3;
}

function dateValue(p: PublicProject): number {
  const d = p.last_action?.date;
  if (!d) return 0;
  return new Date(d).getTime() || 0;
}

export async function loadRegistry(): Promise<PublicRegistry> {
  try {
    const res = await fetch(REGISTRY_URL, { cache: "no-store" });
    if (!res.ok) throw new Error(`registry fetch ${res.status}`);
    const data = (await res.json()) as PublicRegistry;
    data.projects.sort((a, b) => {
      const sr = rankStage(a.stage) - rankStage(b.stage);
      if (sr !== 0) return sr;
      return dateValue(b) - dateValue(a);
    });
    return data;
  } catch (err) {
    console.warn("[registry] fetch failed, using empty:", err);
    return { generated_at: "", count: 0, projects: [] };
  }
}
